trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

variables:
  buildConfiguration: 'release'

pool:
  vmImage: 'windows-latest'

jobs:
- job: 'BuildAndPublish'
  workspace:
    clean: all
  steps:
  - task: DownloadSecureFile@1
    name: downloadSchemaV1103
    displayName: 'Download contract_corporate_schema_v11.03.xsd'
    inputs:
      secureFile: contract_corporate_schema_v11.03.xsd

  - task: DownloadSecureFile@1
    name: downloadSchemaV1104
    displayName: 'Download contract_corporate_schema_v11.04.xsd'
    inputs:
      secureFile: contract_corporate_schema_v11.04.xsd

  - task: DownloadSecureFile@1
    name: downloadSchemaV1105
    displayName: 'Download contract_corporate_schema_v11.05.xsd'
    inputs:
      secureFile: contract_corporate_schema_v11.05.xsd
  
  - task: DownloadSecureFile@1
    name: downloadSchemaV1106
    displayName: 'Download contract_corporate_schema_v11.06.xsd'
    inputs:
      secureFile: contract_corporate_schema_v11.06.xsd

  - task: DownloadSecureFile@1
    name: downloadSchemaV1107
    displayName: 'Download contract_corporate_schema_v11.07.xsd'
    inputs:
      secureFile: contract_corporate_schema_v11.07.xsd

  - task: DownloadSecureFile@1
    name: downloadSchemaV1108
    displayName: 'Download contract_corporate_schema_v11.08.xsd'
    inputs:
      secureFile: contract_corporate_schema_v11.08.xsd

  - task: PowerShell@2
    inputs:
        targetType: inline
        script: |
          Write-Host "Copying schema 11_03 to destination directory"
          $sourceDestination = "$(System.DefaultWorkingDirectory)\Pds.Contracts.FeedProcessor\Pds.Contracts.FeedProcessor.Services\Schema\11_03"

          Write-Host "Copying schema file from $(downloadSchemaV1103.secureFilePath) to target '$sourceDestination\contract_corporate_schema_v11.03.xsd'"

          if(-not (Test-Path -Path "$sourceDestination")) {
            New-Item -Type Directory -Path "$sourceDestination"
          }

          Copy-Item -Path "$(downloadSchemaV1103.secureFilePath)" -Destination "$sourceDestination\contract_corporate_schema_v11.03.xsd"
          Write-Host "File copied!"

          Write-Host "Copying schema 11_04 to destination directory"
          $sourceDestination = "$(System.DefaultWorkingDirectory)\Pds.Contracts.FeedProcessor\Pds.Contracts.FeedProcessor.Services\Schema\11_04"

          Write-Host "Copying schema file from $(downloadSchemaV1104.secureFilePath) to target '$sourceDestination\contract_corporate_schema_v11.04.xsd'"

          if(-not (Test-Path -Path "$sourceDestination")) {
            New-Item -Type Directory -Path "$sourceDestination"
          }

          Copy-Item -Path "$(downloadSchemaV1104.secureFilePath)" -Destination "$sourceDestination\contract_corporate_schema_v11.04.xsd"
          Write-Host "File copied!"

          Write-Host "Copying schema 11_05 to destination directory"
          $sourceDestination = "$(System.DefaultWorkingDirectory)\Pds.Contracts.FeedProcessor\Pds.Contracts.FeedProcessor.Services\Schema\11_05"

          Write-Host "Copying schema file from $(downloadSchemaV1105.secureFilePath) to target '$sourceDestination\contract_corporate_schema_v11.05.xsd'"

          if(-not (Test-Path -Path "$sourceDestination")) {
            New-Item -Type Directory -Path "$sourceDestination"
          }

          Copy-Item -Path "$(downloadSchemaV1105.secureFilePath)" -Destination "$sourceDestination\contract_corporate_schema_v11.05.xsd"
          Write-Host "File copied!"

          Write-Host "Copying schema 11_06 to destination directory"
          $sourceDestination = "$(System.DefaultWorkingDirectory)\Pds.Contracts.FeedProcessor\Pds.Contracts.FeedProcessor.Services\Schema\11_06"

          Write-Host "Copying schema file from $(downloadSchemaV1106.secureFilePath) to target '$sourceDestination\contract_corporate_schema_v11.06.xsd'"

          if(-not (Test-Path -Path "$sourceDestination")) {
            New-Item -Type Directory -Path "$sourceDestination"
          }

          Copy-Item -Path "$(downloadSchemaV1106.secureFilePath)" -Destination "$sourceDestination\contract_corporate_schema_v11.06.xsd"
          Write-Host "File copied!"

          Write-Host "Copying schema 11_07 to destination directory"
          $sourceDestination = "$(System.DefaultWorkingDirectory)\Pds.Contracts.FeedProcessor\Pds.Contracts.FeedProcessor.Services\Schema\11_07"

          Write-Host "Copying schema file from $(downloadSchemaV1107.secureFilePath) to target '$sourceDestination\contract_corporate_schema_v11.07.xsd'"

          if(-not (Test-Path -Path "$sourceDestination")) {
            New-Item -Type Directory -Path "$sourceDestination"
          }

          Copy-Item -Path "$(downloadSchemaV1107.secureFilePath)" -Destination "$sourceDestination\contract_corporate_schema_v11.07.xsd"
          Write-Host "File copied!"

          Write-Host "Copying schema 11_08 to destination directory"
          $sourceDestination = "$(System.DefaultWorkingDirectory)\Pds.Contracts.FeedProcessor\Pds.Contracts.FeedProcessor.Services\Schema\11_08"

          Write-Host "Copying schema file from $(downloadSchemaV1108.secureFilePath) to target '$sourceDestination\contract_corporate_schema_v11.08.xsd'"

          if(-not (Test-Path -Path "$sourceDestination")) {
            New-Item -Type Directory -Path "$sourceDestination"
          }

          Copy-Item -Path "$(downloadSchemaV1108.secureFilePath)" -Destination "$sourceDestination\contract_corporate_schema_v11.08.xsd"
          Write-Host "File copied!"

  - task: UseDotNet@2
    displayName: Select dotnet core 3.1.x
    inputs:
      packageType: sdk
      version: '3.1.x'

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '**/*.csproj'
      feedsToUse: 'select'
      vstsFeed: '9fd46a3f-eada-41dc-86e9-36332aeb8ef1/ecd5af68-0566-42db-8cd7-e71176254aa2'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: '**/*Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration) --no-build --collect "Code coverage" --filter TestCategory=Unit'

  - task: DotNetCoreCLI@2
    displayName: 'Publish Website'
    inputs:
      command: publish
      publishWebProjects: false
      zipAfterPublish: true
      projects: |
        Pds.Contracts.FeedProcessor/Pds.Contracts.FeedProcessor.Func/Pds.Contracts.FeedProcessor.Func.csproj
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      contents: |
        azure/**
      targetFolder: '$(build.artifactstagingdirectory)/publish'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      pathtoPublish: '$(build.artifactstagingdirectory)/publish'